// Recipe database + ingredient knowledge.
// Ingredient names are canonical (lowercase, singular, Aussie terms).
// Salt, pepper and cooking oil are assumed pantry staples and never listed.

export const MOODS = [
  { id: 'notsure', label: 'Not sure — pick for me', emoji: '🤷' },
  { id: 'comfort', label: 'Comfort food', emoji: '🛋️' },
  { id: 'healthy', label: 'Healthy', emoji: '🥗' },
  { id: 'quick', label: 'Quick & easy', emoji: '⚡' },
  { id: 'fancy', label: 'Date night', emoji: '🕯️' },
  { id: 'adventurous', label: 'Adventurous', emoji: '🌏' },
  { id: 'cozy', label: 'Cozy night in', emoji: '🔥' },
  { id: 'light', label: 'Light & fresh', emoji: '🍃' },
  { id: 'indulgent', label: 'Treat yourself', emoji: '🍫' },
  { id: 'family', label: 'Family dinner', emoji: '👨‍👩‍👧‍👦' },
];

// Cuisine styles for the "craving a style?" filter. Each style matches one or
// more recipe `cuisine` values, so broad styles (Asian) overlap specific ones (Japanese).
export const CUISINE_STYLES = [
  { id: 'asian', label: 'Asian', emoji: '🥢', cuisines: ['Asian', 'Chinese', 'Japanese', 'Thai', 'Malaysian'] },
  { id: 'japanese', label: 'Japanese', emoji: '🍱', cuisines: ['Japanese'] },
  { id: 'thai', label: 'Thai', emoji: '🌶️', cuisines: ['Thai', 'Malaysian'] },
  { id: 'italian', label: 'Italian', emoji: '🍝', cuisines: ['Italian'] },
  { id: 'indian', label: 'Indian', emoji: '🍛', cuisines: ['Indian'] },
  { id: 'mexican', label: 'Mexican', emoji: '🌮', cuisines: ['Mexican', 'Tex-Mex'] },
  { id: 'mediterranean', label: 'Mediterranean', emoji: '🫒', cuisines: ['Greek', 'Middle Eastern'] },
  { id: 'western', label: 'Western classics', emoji: '🍖', cuisines: ['Classic', 'British', 'American', 'French', 'Modern'] },
  { id: 'sweet', label: 'Sweet & brekkie', emoji: '🧁', cuisines: ['Baking', 'Dessert', 'Breakfast'] },
];

// Common ingredients offered as quick-add suggestions, grouped for the picker.
export const INGREDIENT_GROUPS = [
  {
    label: 'Proteins',
    items: ['chicken', 'beef', 'beef mince', 'pork', 'bacon', 'salmon', 'prawn', 'white fish', 'egg', 'tofu', 'chickpeas', 'lentils', 'sausage'],
  },
  {
    label: 'Veggies',
    items: ['onion', 'garlic', 'tomato', 'potato', 'carrot', 'capsicum', 'mushroom', 'spinach', 'broccoli', 'zucchini', 'corn', 'pumpkin', 'cauliflower', 'avocado', 'cucumber', 'peas', 'eggplant', 'kale', 'sweet potato'],
  },
  {
    label: 'Carbs & pantry',
    items: ['rice', 'pasta', 'noodles', 'spaghetti', 'bread', 'tortilla', 'flour', 'oats', 'couscous', 'quinoa', 'breadcrumbs', 'canned tomatoes', 'coconut milk', 'stock', 'soy sauce', 'curry paste', 'honey', 'peanut butter'],
  },
  {
    label: 'Dairy & extras',
    items: ['cheese', 'parmesan', 'feta', 'butter', 'milk', 'cream', 'yoghurt', 'lemon', 'lime', 'chilli', 'ginger', 'basil', 'coriander', 'banana', 'chocolate', 'sugar'],
  },
];

// Aliases map user input to canonical names.
export const ALIASES = {
  'chicken breast': 'chicken', 'chicken thigh': 'chicken', 'chicken thighs': 'chicken',
  'mince': 'beef mince', 'minced beef': 'beef mince', 'ground beef': 'beef mince',
  'prawns': 'prawn', 'shrimp': 'prawn', 'shrimps': 'prawn',
  'eggs': 'egg', 'tomatoes': 'tomato', 'cherry tomatoes': 'tomato',
  'onions': 'onion', 'red onion': 'onion', 'brown onion': 'onion', 'spring onion': 'onion',
  'potatoes': 'potato', 'spuds': 'potato', 'carrots': 'carrot',
  'capsicums': 'capsicum', 'bell pepper': 'capsicum', 'bell peppers': 'capsicum', 'peppers': 'capsicum',
  'mushrooms': 'mushroom', 'zucchinis': 'zucchini', 'courgette': 'zucchini',
  'chick peas': 'chickpeas', 'chickpea': 'chickpeas', 'garbanzo beans': 'chickpeas',
  'lentil': 'lentils', 'noodle': 'noodles', 'egg noodles': 'noodles', 'ramen': 'noodles',
  'tinned tomatoes': 'canned tomatoes', 'passata': 'canned tomatoes', 'tomato sauce': 'canned tomatoes',
  'chicken stock': 'stock', 'beef stock': 'stock', 'vegetable stock': 'stock', 'broth': 'stock',
  'lemons': 'lemon', 'limes': 'lime', 'chillies': 'chilli', 'chili': 'chilli', 'chilies': 'chilli',
  'cheddar': 'cheese', 'mozzarella': 'cheese', 'tasty cheese': 'cheese',
  'greek yoghurt': 'yoghurt', 'yogurt': 'yoghurt', 'greek yogurt': 'yoghurt',
  'bananas': 'banana', 'choc': 'chocolate', 'dark chocolate': 'chocolate', 'choc chips': 'chocolate',
  'rolled oats': 'oats', 'porridge': 'oats', 'kumara': 'sweet potato',
  'fish': 'white fish', 'snapper': 'white fish', 'barramundi': 'white fish', 'cod': 'white fish',
  'sausages': 'sausage', 'snags': 'sausage', 'aubergine': 'eggplant',
  'wraps': 'tortilla', 'wrap': 'tortilla', 'tortillas': 'tortilla',
  'coriander leaves': 'coriander', 'cilantro': 'coriander',
  'thai curry paste': 'curry paste', 'red curry paste': 'curry paste', 'green curry paste': 'curry paste',
};

// Each recipe includes `steps` (a simple home-cook method) and `source` — a
// reference link to full tested versions on a reputable recipe site.
export const RECIPES = [
  {
    id: 'spag-bol', name: 'Spaghetti Bolognese', emoji: '🍝', cuisine: 'Italian',
    time: 45, difficulty: 'Easy', serves: 4, moods: ['comfort', 'family', 'cozy'],
    ingredients: ['spaghetti', 'beef mince', 'onion', 'garlic', 'canned tomatoes', 'carrot'],
    optional: ['parmesan', 'basil', 'celery'],
    blurb: 'The weeknight classic — rich beef ragu simmered with tomato and served over spaghetti.',
    steps: [
      'Sauté diced onion, garlic and grated carrot in olive oil until soft.',
      'Add beef mince and brown well, breaking it up as you go.',
      'Stir in canned tomatoes, season, and simmer 20–30 min until thick.',
      'Cook spaghetti in salted water; toss with the sauce and a splash of pasta water.',
      'Serve topped with parmesan and basil.',
    ],
    source: { label: 'RecipeTin Eats — Spaghetti Bolognese', url: 'https://www.recipetineats.com/?s=spaghetti+bolognese' },
  },
  {
    id: 'chicken-stirfry', name: 'Chicken & Veggie Stir-fry', emoji: '🥡', cuisine: 'Asian',
    time: 20, difficulty: 'Easy', serves: 4, moods: ['quick', 'healthy', 'family'],
    ingredients: ['chicken', 'soy sauce', 'garlic', 'broccoli', 'capsicum', 'rice'],
    optional: ['ginger', 'honey', 'chilli', 'carrot'],
    blurb: 'Hot wok, ten minutes of sizzling, dinner done. Endlessly flexible with whatever veg you have.',
    steps: [
      'Cook rice. Slice chicken thinly and toss with a splash of soy sauce.',
      'Stir-fry chicken in a very hot wok until golden; set aside.',
      'Stir-fry broccoli, capsicum and garlic 2–3 min until crisp-tender.',
      'Return chicken with soy sauce (and honey/ginger if using); toss 1 min.',
      'Serve over rice.',
    ],
    source: { label: 'RecipeTin Eats — Chicken Stir Fry', url: 'https://www.recipetineats.com/?s=chicken+stir+fry' },
  },
  {
    id: 'fried-rice', name: 'Egg Fried Rice', emoji: '🍚', cuisine: 'Asian',
    time: 15, difficulty: 'Easy', serves: 2, moods: ['quick', 'comfort'],
    ingredients: ['rice', 'egg', 'soy sauce', 'onion', 'peas'],
    optional: ['bacon', 'corn', 'carrot', 'prawn'],
    blurb: 'The best use of leftover rice known to humankind. Day-old rice fries up best.',
    steps: [
      'Scramble eggs in a hot oiled wok; set aside.',
      'Fry onion (and bacon/prawns if using) until golden.',
      'Add cold cooked rice, pressing and tossing over high heat until toasty.',
      'Add peas, soy sauce and the egg; toss until everything is coated and hot.',
    ],
    source: { label: 'RecipeTin Eats — Egg Fried Rice', url: 'https://www.recipetineats.com/?s=egg+fried+rice' },
  },
  {
    id: 'butter-chicken', name: 'Butter Chicken', emoji: '🍛', cuisine: 'Indian',
    time: 50, difficulty: 'Medium', serves: 4, moods: ['comfort', 'cozy', 'indulgent'],
    ingredients: ['chicken', 'butter', 'cream', 'canned tomatoes', 'garlic', 'ginger', 'rice'],
    optional: ['yoghurt', 'coriander'],
    blurb: 'Silky, gently spiced tomato-cream curry. Better than takeaway and half the price.',
    steps: [
      'Marinate chopped chicken in yoghurt, garlic, ginger and garam masala (30 min if you can).',
      'Sear chicken in butter until golden; set aside.',
      'Simmer canned tomatoes with more butter, garlic and ginger 10 min; blend until smooth.',
      'Return chicken, stir in cream, simmer 10 min until tender.',
      'Serve with rice and coriander.',
    ],
    source: { label: 'RecipeTin Eats — Butter Chicken', url: 'https://www.recipetineats.com/?s=butter+chicken' },
  },
  {
    id: 'thai-green-curry', name: 'Thai Green Curry', emoji: '🍲', cuisine: 'Thai',
    time: 30, difficulty: 'Easy', serves: 4, moods: ['adventurous', 'cozy'],
    ingredients: ['chicken', 'curry paste', 'coconut milk', 'rice'],
    optional: ['capsicum', 'zucchini', 'lime', 'coriander', 'chilli'],
    blurb: 'Fragrant coconut curry that comes together in one pot in half an hour.',
    steps: [
      'Fry curry paste in a little oil until fragrant.',
      'Add half the coconut milk and simmer until it splits and thickens.',
      'Add sliced chicken; cook 5 min. Add remaining coconut milk and veg.',
      'Simmer until chicken is cooked and veg tender; finish with lime juice.',
      'Serve with jasmine rice and coriander.',
    ],
    source: { label: 'RecipeTin Eats — Thai Green Curry', url: 'https://www.recipetineats.com/?s=thai+green+curry' },
  },
  {
    id: 'salmon-tray', name: 'Honey-Soy Salmon Tray Bake', emoji: '🐟', cuisine: 'Modern',
    time: 25, difficulty: 'Easy', serves: 2, moods: ['healthy', 'quick', 'fancy'],
    ingredients: ['salmon', 'honey', 'soy sauce', 'broccoli', 'garlic'],
    optional: ['ginger', 'lime', 'rice', 'sesame seeds'],
    blurb: 'Everything on one tray, into the oven, done. Sticky glaze, crispy edges, zero washing up.',
    steps: [
      'Heat oven to 200°C. Whisk honey, soy, garlic (and ginger) into a glaze.',
      'Arrange salmon and broccoli on a lined tray; brush everything with glaze.',
      'Bake 12–15 min until salmon flakes and broccoli edges crisp.',
      'Spoon over remaining glaze; serve with rice and a squeeze of lime.',
    ],
    source: { label: 'taste.com.au — Honey Soy Salmon', url: 'https://www.taste.com.au/search-recipes?q=honey%20soy%20salmon' },
  },
  {
    id: 'tacos', name: 'Beef Tacos', emoji: '🌮', cuisine: 'Mexican',
    time: 25, difficulty: 'Easy', serves: 4, moods: ['family', 'quick', 'comfort'],
    ingredients: ['beef mince', 'tortilla', 'onion', 'tomato', 'cheese'],
    optional: ['avocado', 'lime', 'coriander', 'lettuce', 'corn'],
    blurb: 'Build-your-own taco night. Spiced beef, fresh toppings, happy table.',
    steps: [
      'Fry diced onion until soft; add mince and brown well.',
      'Season with cumin, paprika, oregano and a splash of water; simmer 5 min.',
      'Warm tortillas in a dry pan.',
      'Serve beef with diced tomato, cheese and your toppings — everyone builds their own.',
    ],
    source: { label: 'RecipeTin Eats — Beef Tacos', url: 'https://www.recipetineats.com/?s=beef+tacos' },
  },
  {
    id: 'carbonara', name: 'Pasta Carbonara', emoji: '🥓', cuisine: 'Italian',
    time: 20, difficulty: 'Medium', serves: 2, moods: ['comfort', 'indulgent', 'quick'],
    ingredients: ['spaghetti', 'bacon', 'egg', 'parmesan', 'garlic'],
    optional: ['cream'],
    blurb: 'Silky egg-and-parmesan sauce clinging to hot pasta with crispy bacon. No cream needed (but we won\'t tell).',
    steps: [
      'Whisk eggs with grated parmesan and lots of black pepper.',
      'Fry bacon with garlic until crisp; kill the heat.',
      'Cook spaghetti; reserve a mug of pasta water.',
      'Toss hot pasta into the bacon pan, then stir in the egg mix off the heat, loosening with pasta water until silky.',
    ],
    source: { label: 'BBC Good Food — Carbonara', url: 'https://www.bbcgoodfood.com/search?q=carbonara' },
  },
  {
    id: 'chickpea-curry', name: 'Chickpea & Spinach Curry', emoji: '🥘', cuisine: 'Indian',
    time: 30, difficulty: 'Easy', serves: 4, moods: ['healthy', 'cozy', 'adventurous'],
    ingredients: ['chickpeas', 'spinach', 'coconut milk', 'onion', 'garlic', 'canned tomatoes'],
    optional: ['ginger', 'rice', 'chilli', 'coriander'],
    blurb: 'Hearty vegetarian curry from the pantry. Cheap, filling and genuinely delicious.',
    steps: [
      'Sauté onion, garlic (and ginger) until golden; add curry powder or garam masala.',
      'Add canned tomatoes; simmer 5 min.',
      'Stir in drained chickpeas and coconut milk; simmer 15 min.',
      'Fold through spinach until wilted; serve with rice.',
    ],
    source: { label: 'BBC Good Food — Chickpea Curry', url: 'https://www.bbcgoodfood.com/search?q=chickpea%20spinach%20curry' },
  },
  {
    id: 'stir-fry-noodles', name: 'Garlic Prawn Noodles', emoji: '🍜', cuisine: 'Asian',
    time: 15, difficulty: 'Easy', serves: 2, moods: ['quick', 'fancy', 'light'],
    ingredients: ['prawn', 'noodles', 'garlic', 'soy sauce', 'chilli'],
    optional: ['lime', 'coriander', 'ginger', 'onion'],
    blurb: 'Fifteen-minute garlicky prawn noodles with a chilli kick. Faster than delivery.',
    steps: [
      'Cook noodles per packet; drain.',
      'Fry lots of sliced garlic and chilli in oil until just golden.',
      'Add prawns; cook 2 min until pink.',
      'Toss in noodles and soy sauce; finish with lime and coriander.',
    ],
    source: { label: 'taste.com.au — Garlic Prawn Noodles', url: 'https://www.taste.com.au/search-recipes?q=garlic%20prawn%20noodles' },
  },
  {
    id: 'roast-chicken', name: 'Sunday Roast Chicken', emoji: '🍗', cuisine: 'Classic',
    time: 90, difficulty: 'Medium', serves: 6, moods: ['family', 'comfort', 'cozy'],
    ingredients: ['chicken', 'potato', 'carrot', 'butter', 'garlic', 'lemon'],
    optional: ['pumpkin', 'onion', 'rosemary', 'stock'],
    blurb: 'Golden roast chook with crispy potatoes. The Sunday ritual worth keeping.',
    steps: [
      'Heat oven to 200°C. Rub chicken with softened butter, salt and pepper; stuff with lemon and garlic.',
      'Surround with chunked potatoes and carrots tossed in oil.',
      'Roast ~1 hr 15 min (until juices run clear), turning veg halfway.',
      'Rest chicken 10 min under foil before carving; crisp the veg meanwhile.',
    ],
    source: { label: 'RecipeTin Eats — Roast Chicken', url: 'https://www.recipetineats.com/?s=roast+chicken' },
  },
  {
    id: 'shakshuka', name: 'Shakshuka', emoji: '🍳', cuisine: 'Middle Eastern',
    time: 30, difficulty: 'Easy', serves: 2, moods: ['adventurous', 'cozy', 'healthy'],
    ingredients: ['egg', 'canned tomatoes', 'onion', 'capsicum', 'garlic'],
    optional: ['feta', 'bread', 'chilli', 'coriander'],
    blurb: 'Eggs poached in a spiced tomato-capsicum sauce. Breakfast, lunch or dinner — it always works.',
    steps: [
      'Sauté onion, capsicum and garlic with cumin and paprika until soft.',
      'Add canned tomatoes; simmer 10 min until thick.',
      'Make wells and crack in the eggs; cover and cook until whites set.',
      'Top with feta and coriander; serve with bread for dunking.',
    ],
    source: { label: 'BBC Good Food — Shakshuka', url: 'https://www.bbcgoodfood.com/search?q=shakshuka' },
  },
  {
    id: 'pumpkin-soup', name: 'Roast Pumpkin Soup', emoji: '🎃', cuisine: 'Classic',
    time: 45, difficulty: 'Easy', serves: 4, moods: ['cozy', 'healthy', 'comfort'],
    ingredients: ['pumpkin', 'onion', 'garlic', 'stock', 'cream'],
    optional: ['bread', 'ginger'],
    blurb: 'Velvety roasted pumpkin soup — winter in a bowl with buttered toast on the side.',
    steps: [
      'Roast chunked pumpkin at 200°C until caramelised (~30 min).',
      'Sauté onion and garlic; add pumpkin and stock.',
      'Simmer 10 min, then blend until silky.',
      'Stir through cream; serve with buttered toast.',
    ],
    source: { label: 'RecipeTin Eats — Pumpkin Soup', url: 'https://www.recipetineats.com/?s=pumpkin+soup' },
  },
  {
    id: 'fish-tacos', name: 'Crispy Fish Tacos', emoji: '🐠', cuisine: 'Mexican',
    time: 30, difficulty: 'Medium', serves: 4, moods: ['light', 'adventurous', 'family'],
    ingredients: ['white fish', 'tortilla', 'lime', 'avocado', 'yoghurt'],
    optional: ['coriander', 'chilli', 'cucumber', 'flour'],
    blurb: 'Golden fish, zingy lime crema and creamy avocado in warm tortillas.',
    steps: [
      'Mix yoghurt with lime juice and a little garlic for the crema.',
      'Dust fish pieces in seasoned flour; pan-fry until golden and flaky.',
      'Warm tortillas; smash avocado with lime and salt.',
      'Assemble: avocado, fish, crema, coriander and chilli.',
    ],
    source: { label: 'RecipeTin Eats — Fish Tacos', url: 'https://www.recipetineats.com/?s=fish+tacos' },
  },
  {
    id: 'pad-thai-ish', name: 'Peanut Noodles', emoji: '🥜', cuisine: 'Asian',
    time: 20, difficulty: 'Easy', serves: 2, moods: ['quick', 'adventurous', 'comfort'],
    ingredients: ['noodles', 'peanut butter', 'soy sauce', 'garlic', 'lime'],
    optional: ['chicken', 'tofu', 'chilli', 'carrot', 'cucumber'],
    blurb: 'Saucy peanut noodles you can make from the pantry in the time it takes to boil water.',
    steps: [
      'Whisk peanut butter, soy sauce, lime juice, grated garlic and hot water into a sauce.',
      'Cook noodles; drain, reserving a splash of water.',
      'Toss noodles with sauce (and cooked chicken/tofu if using), loosening as needed.',
      'Top with cucumber, carrot and chilli.',
    ],
    source: { label: 'BBC Good Food — Peanut Noodles', url: 'https://www.bbcgoodfood.com/search?q=peanut%20noodles' },
  },
  {
    id: 'greek-salad-bowl', name: 'Greek Chicken Bowl', emoji: '🥙', cuisine: 'Greek',
    time: 25, difficulty: 'Easy', serves: 2, moods: ['healthy', 'light', 'quick'],
    ingredients: ['chicken', 'cucumber', 'tomato', 'feta', 'lemon', 'yoghurt'],
    optional: ['couscous', 'rice', 'onion', 'olives'],
    blurb: 'Lemony grilled chicken with crunchy salad, feta and garlicky yoghurt sauce.',
    steps: [
      'Marinate chicken in lemon juice, oregano, garlic and olive oil; grill until charred.',
      'Mix yoghurt with garlic and lemon for the sauce.',
      'Chop cucumber, tomato and onion; crumble in feta.',
      'Bowl it up over couscous or rice; drizzle with the yoghurt sauce.',
    ],
    source: { label: 'RecipeTin Eats — Greek Chicken', url: 'https://www.recipetineats.com/?s=greek+chicken' },
  },
  {
    id: 'mushroom-risotto', name: 'Mushroom Risotto', emoji: '🍄', cuisine: 'Italian',
    time: 45, difficulty: 'Medium', serves: 4, moods: ['fancy', 'cozy', 'comfort'],
    ingredients: ['rice', 'mushroom', 'onion', 'garlic', 'parmesan', 'stock', 'butter'],
    optional: ['cream', 'spinach', 'white wine'],
    blurb: 'Creamy, slow-stirred risotto with golden mushrooms. Pour a glass of wine while you stir.',
    steps: [
      'Fry mushrooms in butter until golden; set aside.',
      'Soften onion and garlic; add arborio rice and toast 1 min (splash of wine if using).',
      'Add hot stock a ladle at a time, stirring, until rice is creamy (~20 min).',
      'Fold in mushrooms, parmesan and a knob of butter; rest 2 min and serve.',
    ],
    source: { label: 'BBC Good Food — Mushroom Risotto', url: 'https://www.bbcgoodfood.com/search?q=mushroom%20risotto' },
  },
  {
    id: 'burgers', name: 'Classic Beef Burgers', emoji: '🍔', cuisine: 'American',
    time: 30, difficulty: 'Easy', serves: 4, moods: ['comfort', 'family', 'indulgent'],
    ingredients: ['beef mince', 'bread', 'cheese', 'onion', 'tomato', 'egg'],
    optional: ['bacon', 'avocado', 'lettuce'],
    blurb: 'Juicy homemade patties, melty cheese, toasted buns. Better than the drive-through.',
    steps: [
      'Mix mince with grated onion, egg, salt and pepper; shape into 4 patties.',
      'Fry or BBQ 3–4 min a side; top with cheese to melt at the end.',
      'Toast the buns cut-side down in the pan.',
      'Stack with tomato, lettuce and your sauces.',
    ],
    source: { label: 'RecipeTin Eats — Beef Burgers', url: 'https://www.recipetineats.com/?s=beef+burgers' },
  },
  {
    id: 'lentil-soup', name: 'Hearty Lentil Soup', emoji: '🍵', cuisine: 'Classic',
    time: 40, difficulty: 'Easy', serves: 4, moods: ['healthy', 'cozy', 'comfort'],
    ingredients: ['lentils', 'carrot', 'onion', 'garlic', 'canned tomatoes', 'stock'],
    optional: ['spinach', 'lemon', 'bread'],
    blurb: 'Thick, warming lentil soup that costs about $2 a bowl and tastes like a hug.',
    steps: [
      'Sauté onion, carrot and garlic with cumin until soft.',
      'Add rinsed lentils, canned tomatoes and stock.',
      'Simmer 25–30 min until lentils are tender, adding water if it gets too thick.',
      'Finish with lemon juice (and spinach); serve with crusty bread.',
    ],
    source: { label: 'RecipeTin Eats — Lentil Soup', url: 'https://www.recipetineats.com/?s=lentil+soup' },
  },
  {
    id: 'pancakes', name: 'Fluffy Pancakes', emoji: '🥞', cuisine: 'Breakfast',
    time: 20, difficulty: 'Easy', serves: 4, moods: ['indulgent', 'family', 'cozy'],
    ingredients: ['flour', 'egg', 'milk', 'butter', 'sugar'],
    optional: ['banana', 'chocolate', 'honey', 'lemon'],
    blurb: 'Weekend-morning stack with butter and your topping of choice. Kids optional.',
    steps: [
      'Whisk 1½ cups flour, 3 tsp baking powder, 2 tbsp sugar and a pinch of salt.',
      'Whisk in 1 egg and 1¼ cups milk until just smooth.',
      'Cook ladles of batter in a buttered pan; flip when bubbles pop.',
      'Stack, butter, and top with whatever makes you happy.',
    ],
    source: { label: 'RecipeTin Eats — Fluffy Pancakes', url: 'https://www.recipetineats.com/?s=fluffy+pancakes' },
  },
  {
    id: 'banana-bread', name: 'Banana Bread', emoji: '🍌', cuisine: 'Baking',
    time: 70, difficulty: 'Easy', serves: 8, moods: ['indulgent', 'cozy', 'comfort'],
    ingredients: ['banana', 'flour', 'egg', 'butter', 'sugar'],
    optional: ['chocolate', 'oats', 'honey'],
    blurb: 'The rightful destiny of every browning banana on your bench.',
    steps: [
      'Heat oven to 180°C. Mash 3 ripe bananas.',
      'Beat in melted butter, sugar and eggs.',
      'Fold in flour, baking soda and a pinch of salt (plus choc chips).',
      'Bake in a lined loaf tin 50–60 min until a skewer comes out clean.',
    ],
    source: { label: 'taste.com.au — Banana Bread', url: 'https://www.taste.com.au/search-recipes?q=banana%20bread' },
  },
  {
    id: 'choc-mug-cake', name: '5-Minute Chocolate Mug Cake', emoji: '🍫', cuisine: 'Dessert',
    time: 5, difficulty: 'Easy', serves: 1, moods: ['indulgent', 'quick'],
    ingredients: ['flour', 'chocolate', 'milk', 'sugar', 'butter'],
    optional: ['egg', 'peanut butter'],
    blurb: 'From craving to warm chocolate cake in five minutes flat. Dangerous knowledge.',
    steps: [
      'In a mug, mix 4 tbsp flour, 2 tbsp cocoa/grated chocolate, 2 tbsp sugar, pinch of baking powder.',
      'Stir in 3 tbsp milk and 1 tbsp melted butter until smooth.',
      'Push a square of chocolate into the middle.',
      'Microwave 60–90 sec until just set. Eat immediately (carefully).',
    ],
    source: { label: 'BBC Good Food — Mug Cake', url: 'https://www.bbcgoodfood.com/search?q=chocolate%20mug%20cake' },
  },
  {
    id: 'steak-night', name: 'Steak with Garlic Butter & Mash', emoji: '🥩', cuisine: 'Classic',
    time: 35, difficulty: 'Medium', serves: 2, moods: ['fancy', 'indulgent', 'comfort'],
    ingredients: ['beef', 'potato', 'butter', 'garlic', 'milk'],
    optional: ['mushroom', 'spinach', 'cream', 'rosemary'],
    blurb: 'Restaurant steak night at home — seared crust, garlic butter, cloud-like mash.',
    steps: [
      'Boil chopped potatoes until tender; mash with butter and warm milk.',
      'Pat steaks dry; season heavily. Sear in a screaming-hot pan 2–3 min a side.',
      'Add butter, crushed garlic (and rosemary); baste the steaks 1 min.',
      'Rest steaks 5 min; serve over mash with the pan butter.',
    ],
    source: { label: 'RecipeTin Eats — Steak with Garlic Butter', url: 'https://www.recipetineats.com/?s=garlic+butter+steak' },
  },
  {
    id: 'tomato-pasta', name: 'Cherry Tomato & Garlic Pasta', emoji: '🍅', cuisine: 'Italian',
    time: 20, difficulty: 'Easy', serves: 2, moods: ['quick', 'light', 'comfort'],
    ingredients: ['pasta', 'tomato', 'garlic', 'basil', 'parmesan'],
    optional: ['chilli', 'spinach', 'feta'],
    blurb: 'Blistered tomatoes, lots of garlic, good olive oil. Simple and perfect.',
    steps: [
      'Cook pasta; reserve a mug of pasta water.',
      'Meanwhile blister halved tomatoes in olive oil with sliced garlic (and chilli).',
      'Crush some tomatoes into a rough sauce; season well.',
      'Toss with pasta, pasta water, basil and parmesan.',
    ],
    source: { label: 'BBC Good Food — Cherry Tomato Pasta', url: 'https://www.bbcgoodfood.com/search?q=cherry%20tomato%20pasta' },
  },
  {
    id: 'chicken-soup', name: 'Chicken Noodle Soup', emoji: '🍲', cuisine: 'Classic',
    time: 40, difficulty: 'Easy', serves: 4, moods: ['cozy', 'comfort', 'healthy'],
    ingredients: ['chicken', 'noodles', 'carrot', 'onion', 'garlic', 'stock'],
    optional: ['ginger', 'corn', 'spinach'],
    blurb: 'The universal cure for cold days, sniffles and general malaise.',
    steps: [
      'Sauté onion, carrot and garlic until soft.',
      'Add stock and chicken; simmer 20 min, then shred the chicken.',
      'Add noodles and cook until tender.',
      'Season, add greens, and ladle up.',
    ],
    source: { label: 'RecipeTin Eats — Chicken Noodle Soup', url: 'https://www.recipetineats.com/?s=chicken+noodle+soup' },
  },
  {
    id: 'quesadillas', name: 'Cheesy Chicken Quesadillas', emoji: '🧀', cuisine: 'Mexican',
    time: 20, difficulty: 'Easy', serves: 2, moods: ['quick', 'comfort', 'family'],
    ingredients: ['tortilla', 'chicken', 'cheese', 'capsicum', 'onion'],
    optional: ['avocado', 'corn', 'chilli', 'yoghurt'],
    blurb: 'Crispy, melty, done in 20. Great way to use up leftover roast chicken.',
    steps: [
      'Sauté sliced onion and capsicum; mix with shredded cooked chicken.',
      'Fill half of each tortilla with the mix and plenty of cheese; fold over.',
      'Dry-fry 2–3 min a side until golden and molten.',
      'Cut into wedges; serve with smashed avo or yoghurt.',
    ],
    source: { label: 'taste.com.au — Chicken Quesadillas', url: 'https://www.taste.com.au/search-recipes?q=chicken%20quesadilla' },
  },
  {
    id: 'buddha-bowl', name: 'Roast Veg Buddha Bowl', emoji: '🥗', cuisine: 'Modern',
    time: 40, difficulty: 'Easy', serves: 2, moods: ['healthy', 'light'],
    ingredients: ['sweet potato', 'chickpeas', 'quinoa', 'avocado', 'lemon'],
    optional: ['spinach', 'kale', 'yoghurt', 'cucumber', 'rice'],
    blurb: 'Roasted veg, crispy chickpeas and grains with a lemony dressing. Meal-prep gold.',
    steps: [
      'Roast cubed sweet potato and drained chickpeas (tossed in oil and paprika) at 200°C ~25 min.',
      'Cook quinoa.',
      'Whisk lemon juice, olive oil and a little honey or yoghurt into a dressing.',
      'Bowl everything with avocado and greens; drizzle generously.',
    ],
    source: { label: 'BBC Good Food — Buddha Bowl', url: 'https://www.bbcgoodfood.com/search?q=buddha%20bowl' },
  },
  {
    id: 'omelette', name: 'Cheese & Mushroom Omelette', emoji: '🍳', cuisine: 'French',
    time: 10, difficulty: 'Easy', serves: 1, moods: ['quick', 'light', 'healthy'],
    ingredients: ['egg', 'cheese', 'mushroom', 'butter'],
    optional: ['spinach', 'tomato', 'onion', 'bacon'],
    blurb: 'Ten minutes, one pan, endlessly adaptable. The emergency meal that never fails.',
    steps: [
      'Fry sliced mushrooms in butter until golden; set aside.',
      'Beat 3 eggs; pour into the buttered pan over medium heat.',
      'Drag the edges in as they set; when nearly done, add cheese and mushrooms.',
      'Fold and slide onto a plate.',
    ],
    source: { label: 'BBC Good Food — Omelette', url: 'https://www.bbcgoodfood.com/search?q=mushroom%20omelette' },
  },
  {
    id: 'san-choy-bow', name: 'San Choy Bow', emoji: '🥬', cuisine: 'Chinese',
    time: 20, difficulty: 'Easy', serves: 4, moods: ['light', 'healthy', 'adventurous'],
    ingredients: ['pork', 'soy sauce', 'garlic', 'ginger', 'lettuce'],
    optional: ['mushroom', 'corn', 'chilli', 'noodles'],
    blurb: 'Sizzling pork mince in crisp lettuce cups — light, fresh and full of flavour.',
    steps: [
      'Stir-fry garlic and ginger; add pork mince and brown well.',
      'Add soy sauce, a little sugar and diced mushrooms/corn; toss 2 min.',
      'Separate lettuce leaves into cups.',
      'Spoon in the pork; top with chilli and eat with your hands.',
    ],
    source: { label: 'RecipeTin Eats — San Choy Bow', url: 'https://www.recipetineats.com/?s=san+choy+bow' },
  },
  {
    id: 'frittata', name: 'Leftover-Veg Frittata', emoji: '🥧', cuisine: 'Italian',
    time: 30, difficulty: 'Easy', serves: 4, moods: ['healthy', 'family', 'light'],
    ingredients: ['egg', 'cheese', 'potato', 'onion', 'spinach'],
    optional: ['bacon', 'zucchini', 'capsicum', 'feta', 'mushroom'],
    blurb: 'The fridge-clearing hero. Whatever veg is wilting, it belongs in here.',
    steps: [
      'Sauté onion and cooked potato (plus any veg) in an ovenproof pan.',
      'Whisk 8 eggs with cheese; pour over the veg.',
      'Cook on low until the edges set, then finish under the grill until golden.',
      'Rest 5 min, slice into wedges.',
    ],
    source: { label: 'taste.com.au — Frittata', url: 'https://www.taste.com.au/search-recipes?q=vegetable%20frittata' },
  },
  {
    id: 'laksa-ish', name: 'Quick Coconut Noodle Soup', emoji: '🍜', cuisine: 'Malaysian',
    time: 25, difficulty: 'Easy', serves: 2, moods: ['adventurous', 'cozy', 'quick'],
    ingredients: ['noodles', 'coconut milk', 'curry paste', 'stock', 'lime'],
    optional: ['prawn', 'chicken', 'tofu', 'chilli', 'coriander'],
    blurb: 'Laksa-style coconut broth with slurpy noodles. Add prawns or tofu and go.',
    steps: [
      'Fry curry paste until fragrant; add coconut milk and stock.',
      'Simmer 10 min; add prawns/chicken/tofu and cook through.',
      'Cook noodles separately; divide between bowls.',
      'Ladle over the broth; finish with lime, chilli and coriander.',
    ],
    source: { label: 'RecipeTin Eats — Laksa', url: 'https://www.recipetineats.com/?s=laksa' },
  },
  {
    id: 'cottage-pie', name: 'Cottage Pie', emoji: '🥧', cuisine: 'British',
    time: 60, difficulty: 'Medium', serves: 6, moods: ['comfort', 'family', 'cozy'],
    ingredients: ['beef mince', 'potato', 'carrot', 'onion', 'stock', 'butter'],
    optional: ['peas', 'cheese', 'canned tomatoes'],
    blurb: 'Rich beef and gravy under a golden mashed potato lid. Winter\'s greatest hit.',
    steps: [
      'Brown mince with onion and carrot; stir in flour, then stock (and tomatoes).',
      'Simmer 20 min into a thick gravy; add peas.',
      'Boil and mash potatoes with butter.',
      'Top the beef with mash, rough up with a fork, and bake at 200°C until golden.',
    ],
    source: { label: 'RecipeTin Eats — Cottage Pie', url: 'https://www.recipetineats.com/?s=cottage+pie' },
  },
  {
    id: 'halloumi-salad', name: 'Grilled Halloumi & Avocado Salad', emoji: '🥑', cuisine: 'Modern',
    time: 15, difficulty: 'Easy', serves: 2, moods: ['light', 'healthy', 'quick'],
    ingredients: ['feta', 'avocado', 'tomato', 'cucumber', 'lemon'],
    optional: ['quinoa', 'spinach', 'honey', 'bread'],
    blurb: 'Golden grilled cheese (the fancy kind) over a crunchy fresh salad.',
    steps: [
      'Chop tomato, cucumber and avocado; dress with lemon juice and olive oil.',
      'Slice halloumi/feta thickly; grill or pan-fry until golden on both sides.',
      'Pile the warm cheese onto the salad; drizzle with honey if you like.',
    ],
    source: { label: 'BBC Good Food — Halloumi Salad', url: 'https://www.bbcgoodfood.com/search?q=halloumi%20salad' },
  },
  {
    id: 'garlic-bread-soup-night', name: 'Tomato Soup & Garlic Bread', emoji: '🍞', cuisine: 'Classic',
    time: 30, difficulty: 'Easy', serves: 4, moods: ['cozy', 'comfort', 'quick'],
    ingredients: ['canned tomatoes', 'onion', 'garlic', 'stock', 'bread', 'butter'],
    optional: ['cream', 'basil', 'cheese'],
    blurb: 'Rainy-day double act: silky tomato soup with crunchy golden garlic bread for dunking.',
    steps: [
      'Sauté onion and garlic; add canned tomatoes and stock.',
      'Simmer 15 min, then blend smooth; stir in cream if using.',
      'Mix butter with crushed garlic; spread on bread and grill until golden.',
      'Dunk enthusiastically.',
    ],
    source: { label: 'BBC Good Food — Tomato Soup', url: 'https://www.bbcgoodfood.com/search?q=tomato%20soup' },
  },
  {
    id: 'teriyaki-bowl', name: 'Teriyaki Chicken Bowl', emoji: '🍱', cuisine: 'Japanese',
    time: 25, difficulty: 'Easy', serves: 2, moods: ['quick', 'comfort', 'healthy'],
    ingredients: ['chicken', 'soy sauce', 'honey', 'rice', 'ginger', 'garlic'],
    optional: ['broccoli', 'cucumber', 'sesame seeds', 'avocado'],
    blurb: 'Sticky-glazed chicken over rice with something green. Weeknight MVP.',
    steps: [
      'Cook rice. Whisk soy sauce, honey, grated ginger and garlic.',
      'Pan-fry chopped chicken until golden.',
      'Pour in the sauce; bubble until sticky and glossy.',
      'Serve over rice with steamed broccoli and sesame seeds.',
    ],
    source: { label: 'RecipeTin Eats — Teriyaki Chicken', url: 'https://www.recipetineats.com/?s=teriyaki+chicken' },
  },
  {
    id: 'eggplant-parm', name: 'Eggplant Parmigiana', emoji: '🍆', cuisine: 'Italian',
    time: 60, difficulty: 'Medium', serves: 4, moods: ['comfort', 'fancy', 'cozy'],
    ingredients: ['eggplant', 'canned tomatoes', 'cheese', 'parmesan', 'garlic', 'basil'],
    optional: ['breadcrumbs', 'pasta', 'egg', 'flour'],
    blurb: 'Layers of golden eggplant, rich tomato sauce and molten cheese. Vegetarian and glorious.',
    steps: [
      'Slice eggplant; salt 20 min, pat dry, then fry or roast until golden.',
      'Simmer canned tomatoes with garlic and basil into a sauce.',
      'Layer eggplant, sauce, cheese and parmesan in a baking dish; repeat.',
      'Bake at 190°C ~30 min until bubbling and golden.',
    ],
    source: { label: 'RecipeTin Eats — Eggplant Parmigiana', url: 'https://www.recipetineats.com/?s=eggplant+parmigiana' },
  },
  {
    id: 'nachos', name: 'Loaded Nachos', emoji: '🧀', cuisine: 'Tex-Mex',
    time: 25, difficulty: 'Easy', serves: 4, moods: ['indulgent', 'family', 'comfort'],
    ingredients: ['beef mince', 'cheese', 'corn', 'avocado', 'canned tomatoes'],
    optional: ['tortilla', 'chilli', 'yoghurt', 'lime', 'coriander'],
    blurb: 'Movie-night mountain of crunchy, cheesy, spicy goodness. Bring the whole tray to the couch.',
    steps: [
      'Brown mince with taco spices; add canned tomatoes and corn, simmer 10 min.',
      'Layer corn chips, beef and cheese on a tray.',
      'Grill until the cheese is molten.',
      'Top with smashed avo, yoghurt, lime and coriander.',
    ],
    source: { label: 'taste.com.au — Loaded Nachos', url: 'https://www.taste.com.au/search-recipes?q=beef%20nachos' },
  },
  {
    id: 'oat-brekkie', name: 'Banana Honey Porridge', emoji: '🥣', cuisine: 'Breakfast',
    time: 10, difficulty: 'Easy', serves: 1, moods: ['healthy', 'cozy', 'quick'],
    ingredients: ['oats', 'milk', 'banana', 'honey'],
    optional: ['yoghurt', 'peanut butter', 'chocolate'],
    blurb: 'Creamy stovetop porridge with caramelised banana. Cold-morning fuel.',
    steps: [
      'Simmer ½ cup oats with 1 cup milk, stirring, ~5 min until creamy.',
      'Meanwhile fry banana slices in a little butter until caramelised.',
      'Bowl the porridge; top with banana, honey and a dollop of yoghurt.',
    ],
    source: { label: 'BBC Good Food — Porridge', url: 'https://www.bbcgoodfood.com/search?q=banana%20porridge' },
  },
  {
    id: 'tofu-stirfry', name: 'Crispy Tofu Stir-fry', emoji: '🌱', cuisine: 'Asian',
    time: 25, difficulty: 'Easy', serves: 2, moods: ['healthy', 'light', 'adventurous'],
    ingredients: ['tofu', 'soy sauce', 'garlic', 'ginger', 'broccoli', 'rice'],
    optional: ['honey', 'chilli', 'capsicum', 'noodles', 'peanut butter'],
    blurb: 'Golden crispy tofu in a sticky garlic-ginger glaze. Converts tofu sceptics on contact.',
    steps: [
      'Press tofu, cube it, toss in cornflour; shallow-fry until golden all over.',
      'Stir-fry broccoli with garlic and ginger.',
      'Add soy sauce (and honey); return tofu and toss until glazed.',
      'Serve over rice with chilli.',
    ],
    source: { label: 'RecipeTin Eats — Crispy Tofu', url: 'https://www.recipetineats.com/?s=crispy+tofu' },
  },
];
